#include <stdio.h> // Required for getchar, putchar, scanf, printf

int main() {
    char char1, char2, char3, char4; // Declare four character variables

    // -- Part 1: Using getchar() and putchar() ---
    printf("--- Part 1: Using getchar() and putchar() ---\n");
    printf("Please enter a single character: ");
    char1 = getchar(); // Read one character from standard input and store it in char1

    printf("You entered: ");
    putchar(char1); // Print the character stored in char1 to standard output
    printf("\n");

    // Important note about getchar() and the input buffer:
    // When you type a character and press Enter, the character itself
    // is read, but the newline character ('\n') generated by pressing Enter
    // often remains in the input buffer.
    // The next getchar() call will likely read this leftover newline character ('\n').

    printf("Press Enter to continue (this reads the leftover newline character from previous input): ");
    getchar(); // Consume the leftover newline character if present

    // --- Part 2: Using scanf() for character input ---
    printf("\n--- Part 2: scanf('%%c') ---\n");
    printf("Please enter another single character: ");
    scanf("%c", &char2); // Read one character using the %c format specifier

    printf("You entered with scanf: %c\n", char2); // Print the character read by scanf

    // Important note about scanf() and newlines:
    // Similar to getchar(), scanf("%c") reads a character, buf if you enter
    // something and press Enter, the '\n' remains in the buffer.
    // To explicitly consume it for cleaner subsequent inputs:

    printf("Consuming leftover newline after scanf. Press Enter: ");
    scanf("%*c"); // The %*c format specifier in scanf tells the function to read a character but not store it, effectively discarding it

    // --- Part 3: Using printf() for character output ---
    printf("\n--- Part 3: printf() ---\n");
    char3 = 'X'; // Assign a character constant to char3
    printf("Printing a character constant with printf: %c\n", char3); // Print the character stored in char3
    printf("The ASCII value of '%c' is: %d\n", char3, char3); // Print the ASCII value of char3

    // --- Part 4: Combining inputs and showing ASCII values ---
    printf("\n--- Part 4: Combined Example ---\n");
    printf("Enter a character to see its ASCII value: ");
    scanf("%c", &char4); // Read character
    scanf("%*c"); // Consume leftover newline character

    printf("You entered '%c'. Its ASCII value is %d.\n", char4, char4); // Print the character and its ASCII value

    return 0; // Indicate successful completion of the program
}
